"""initial schema

Revision ID: 11f848d3299f
Revises: 
Create Date: 2026-07-06 00:27:59.267385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f848d3299f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_catalog',
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('hue', sa.SmallInteger(), nullable=False),
    sa.Column('saturation', sa.SmallInteger(), nullable=False),
    sa.Column('lightness', sa.SmallInteger(), nullable=False),
    sa.Column('luminance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hex_code')
    )
    op.create_index('idx_color_catalog_hue', 'color_catalog', ['hue'], unique=False)
    op.create_index('idx_color_catalog_lightness', 'color_catalog', ['lightness'], unique=False)
    op.create_index('idx_color_catalog_usage_count', 'color_catalog', ['usage_count'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('palettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('forked_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forked_from'], ['palettes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_palettes_is_public', 'palettes', ['is_public'], unique=False)
    op.create_index('idx_palettes_user_id', 'palettes', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('palette_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'palette_id')
    )
    op.create_table('palette_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palette_id', sa.Integer(), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hex_code'], ['color_catalog.hex_code'], ),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('palette_id', 'position', name='palette_colors_palette_id_position_key')
    )
    op.create_index('idx_palette_colors_hex_code', 'palette_colors', ['hex_code'], unique=False)
    op.create_index('idx_palette_colors_palette_id', 'palette_colors', ['palette_id'], unique=False)
    op.create_table('palette_tags',
    sa.Column('palette_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('palette_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palette_tags')
    op.drop_index('idx_palette_colors_palette_id', table_name='palette_colors')
    op.drop_index('idx_palette_colors_hex_code', table_name='palette_colors')
    op.drop_table('palette_colors')
    op.drop_table('favorites')
    op.drop_index('idx_palettes_user_id', table_name='palettes')
    op.drop_index('idx_palettes_is_public', table_name='palettes')
    op.drop_table('palettes')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index('idx_color_catalog_usage_count', table_name='color_catalog')
    op.drop_index('idx_color_catalog_lightness', table_name='color_catalog')
    op.drop_index('idx_color_catalog_hue', table_name='color_catalog')
    op.drop_table('color_catalog')
    # ### end Alembic commands ###
